// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4sI6xyxsibqZecq-GUv5KHTzWYe5kiM',
    appId: '1:293434933844:web:b81b15fd17d21519e3a3c1',
    messagingSenderId: '293434933844',
    projectId: 'aff-paint-store-app',
    authDomain: 'aff-paint-store-app.firebaseapp.com',
    storageBucket: 'aff-paint-store-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eyaYcHMItWY9LcArXRNRgWlBppnWk7E',
    appId: '1:293434933844:android:04c805614201dd55e3a3c1',
    messagingSenderId: '293434933844',
    projectId: 'aff-paint-store-app',
    storageBucket: 'aff-paint-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVYajU4S1ZeKXmEWpdPEbw7G3C2u4yNWI',
    appId: '1:293434933844:ios:5e9adf680f85c4fde3a3c1',
    messagingSenderId: '293434933844',
    projectId: 'aff-paint-store-app',
    storageBucket: 'aff-paint-store-app.firebasestorage.app',
    iosBundleId: 'com.example.affPaintStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVYajU4S1ZeKXmEWpdPEbw7G3C2u4yNWI',
    appId: '1:293434933844:ios:5e9adf680f85c4fde3a3c1',
    messagingSenderId: '293434933844',
    projectId: 'aff-paint-store-app',
    storageBucket: 'aff-paint-store-app.firebasestorage.app',
    iosBundleId: 'com.example.affPaintStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT4sI6xyxsibqZecq-GUv5KHTzWYe5kiM',
    appId: '1:293434933844:web:b37ed120e660f319e3a3c1',
    messagingSenderId: '293434933844',
    projectId: 'aff-paint-store-app',
    authDomain: 'aff-paint-store-app.firebaseapp.com',
    storageBucket: 'aff-paint-store-app.firebasestorage.app',
  );
}
